# -*- coding: utf-8 -*-
"""linear reg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vv0zz1w5tJhnDYL59Kzt-EJB1cD26fZf

Simple regression {Minor project 1}

Importing Required Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Imorting dataset"""

dataset = pd.read_csv('salary_data.csv')

"""Experience array"""

X = dataset.iloc[:, :-1]

"""Salary Array"""

y = dataset.iloc[:, 1]

"""splitting for training set and test set"""

from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)

"""Fitting linear regression to training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""Predicting the test set result"""

y_pred = regressor.predict(X_test)

"""Visualising the Training set result"""

viz_train = plt
viz_train.scatter(X_train, y_train, color='red')
viz_train.plot(X_train, regressor.predict(X_train), color='blue')
viz_train.title('Salary VS Experience (Training set)')
viz_train.xlabel('Year of Experience')
viz_train.ylabel('Salary')
viz_train.show()

"""Visualising the test show result"""

viz_test = plt
viz_test.scatter(X_test, y_test, color='red')
viz_test.plot(X_train, regressor.predict(X_train), color='blue')
viz_test.title('Salary VS Experience (Test set)')
viz_test.xlabel('Year of Experience')
viz_test.ylabel('Salary')
viz_test.show()